[http]
name="http"
port=80

# (string) HTTP request method type
; method=GET

# (string) Send the request to a specific endpoint / path
; endpoint="/"

# (string) Set the user-agent
; user-agent="Mozilla/5.0 zgrab/0.x"

# (bool) Retry with HTTPS if the initial cleartext request fails
; retry-https

# (bool) Use HTTPS for the initial request
; use-https

# (int) Max kilobytes of the response body to read
; max-size=256

# (int) Max number of redirects to follow
; max-redirects=0

# (bool) Treat reaching the redirect limit as success rather than an error
; redirects-succeed

# (string) Send a request body (use --method=POST)
; request-body=""

# (string) Comma-separated extra request header names and their values
; custom-headers-names=""
; custom-headers-values=""
